services:
  app:
    build: .
    ports:
      - "8551:8551"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=123
      - DATABASE_NAME=financas
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: 'financas'
    ports:
      - "20306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./reference/database/implantation_financas.sql:/docker-entrypoint-initdb.d/implantation_financas.sql

volumes:
  mysql_data:
