services:
  app:
    image: expenselit-app
    ports:
      - "8551:8551"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=20306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=123
      - DATABASE_NAME=financas
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql-ptbr
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: 'financas'
    ports:
    - "20306:20306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./reference/database/implantation_financas.sql:/docker-entrypoint-initdb.d/implantation_financas.sql

volumes:
  mysql_data:
