version: '3.8'
services:
  app:
    image: expenselit-app
    ports:
      - "8551:8551"
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=123
      - DATABASE_NAME=financas
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - .:/app

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: 'financas'
    ports:
      - "20306:3306"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - mysql_data:/var/lib/mysql
      - ./reference/database/implantation_financas.sql:/docker-entrypoint-initdb.d/implantation_financas.sql

volumes:
  mysql_data:

