version: "3.9"

services:
  app:
    image: expenselit-app
    ports:
      - "8551:8551"
    env_file:
      - .env
    environment:
      DATABASE_HOST: ${DB_HOSTNAME}
      DATABASE_PORT: ${DB_PORT}
      DATABASE_USER: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_NAME: ${DB_NAME}
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql:8
    ports:
      - "3307:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_RANDOM_ROOT_PASSWORD: "no"
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./reference/database/implantation_financas.sql:/docker-entrypoint-initdb.d/implantation_financas.sql
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh

volumes:
  mysql_data:
