# Tema Claro
# Tema Escuro
# Tema Claro
# Tema Escuro
# Tema Escuro
# Tema Claro
# Tema Escuro
[theme]
primaryColor="#bd93f9"
backgroundColor="#282a36"
secondaryBackgroundColor="#44475a"
textColor="#f8f8f2"
showWidgetBorder=true

[server]
headless = true
enableStaticServing = true

[client]
showSidebarNavigation = false
